import { TermsSection } from "./terms-section"
import { TermsList } from "./terms-list"
import { TermsHighlight } from "./terms-highlight"

export const termsData = [
  {
    id: "acceptance",
    number: "1",
    title: "Acceptance of Terms",
  },
  {
    id: "description",
    number: "2",
    title: "Service Description",
  },
  {
    id: "intellectual-property",
    number: "3",
    title: "Intellectual Property Rights",
  },
  {
    id: "privacy",
    number: "4",
    title: "Privacy & Data Protection",
  },
  {
    id: "termination",
    number: "5",
    title: "Termination",
  },
  {
    id: "disclaimers",
    number: "6",
    title: "Disclaimers",
  },
]

export const AcceptanceSection = () => (
  <TermsSection id="acceptance" number="1" title="Acceptance of Terms">
    <p>
      By accessing or using ChatSecure (&quot;the Service&quot;), you agree to be bound by these 
      Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, you may not access 
      or use the Service.
    </p>
    <p>
      These Terms apply to all visitors, users, and others who access or use the Service. 
      By using the Service, you represent that you are at least 18 years of age, or if you 
      are under 18, that you have obtained parental or guardian consent to use the Service.
    </p>
    <TermsHighlight type="info">
      By clicking &quot;I Agree&quot; or by using the Service, you acknowledge that you have read, 
      understood, and agree to be bound by these Terms.
    </TermsHighlight>
  </TermsSection>
)

export const DescriptionSection = () => (
  <TermsSection id="description" number="2" title="Service Description">
    <p>
      ChatSecure is an AI-powered chat platform that provides intelligent, secure 
      conversational experiences. Our Service includes:
    </p>
    <TermsList 
      items={[
        "AI-powered chat functionality with advanced language models",
        "Secure, encrypted communication channels",
        "Chat history management and export capabilities",
        "API access for developers (subject to separate API terms)",
        "Team collaboration features for enterprise users",
        "Custom integrations and enterprise solutions",
      ]}
    />
    <p>
      We reserve the right to modify, suspend, or discontinue any aspect of the Service 
      at any time without prior notice.
    </p>
  </TermsSection>
)

export const IntellectualPropertySection = () => (
  <TermsSection id="intellectual-property" number="3" title="Intellectual Property Rights">
    <p>
      The Service and its original content, features, and functionality are owned by 
      ChatSecure and are protected by international copyright, trademark, patent, trade 
      secret, and other intellectual property laws.
    </p>
    <p>
      <strong>Your Content:</strong> You retain ownership of any content you submit, post, 
      or display through the Service. By submitting content, you grant ChatSecure a 
      worldwide, non-exclusive, royalty-free license to use, reproduce, and display such 
      content solely for the purpose of providing the Service.
    </p>
    <p>
      <strong>AI-Generated Content:</strong> Content generated by our AI in response to 
      your inputs may be used by you for any lawful purpose, subject to these Terms. 
      However, similar outputs may be generated for other users.
    </p>
  </TermsSection>
)

export const PrivacySection = () => (
  <TermsSection id="privacy" number="4" title="Privacy & Data Protection">
    <p>
      Your privacy is important to us. Our collection and use of personal information is 
      governed by our Privacy Policy, which is incorporated into these Terms by reference.
    </p>
    <TermsList 
      items={[
        "We use 256-bit encryption for all data transmission",
        "Your conversations are not used to train our AI models",
        "You can request deletion of your data at any time",
        "We comply with GDPR, CCPA, and other applicable privacy laws",
        "We do not sell your personal information to third parties",
      ]}
    />
    <TermsHighlight type="success">
      ChatSecure is committed to maintaining the highest standards of data protection 
      and security for all users.
    </TermsHighlight>
  </TermsSection>
)

export const TerminationSection = () => (
  <TermsSection id="termination" number="5" title="Termination">
    <p>
      We may terminate or suspend your account and access to the Service immediately, 
      without prior notice or liability, for any reason, including:
    </p>
    <TermsList 
      items={[
        "Breach of these Terms of Service",
        "Violation of our Acceptable Use Policy",
        "Request by law enforcement or government agencies",
        "Extended periods of inactivity",
        "Unexpected technical or security issues",
      ]}
    />
    <p>
      Upon termination, your right to use the Service will immediately cease. You may 
      request export of your data within 30 days of termination.
    </p>
  </TermsSection>
)

export const DisclaimersSection = () => (
  <TermsSection id="disclaimers" number="6" title="Disclaimers">
    <TermsHighlight type="warning">
      THE SERVICE IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS WITHOUT WARRANTIES 
      OF ANY KIND, EITHER EXPRESS OR IMPLIED.
    </TermsHighlight>
    <p>
      ChatSecure does not warrant that:
    </p>
    <TermsList 
      items={[
        "The Service will be uninterrupted, secure, or error-free",
        "Results obtained from the Service will be accurate or reliable",
        "The quality of the Service will meet your expectations",
        "AI-generated content will be free from errors or biases",
      ]}
    />
    <p>
      You understand and agree that you use the Service at your own risk. AI-generated 
      content should not be relied upon as professional, legal, medical, or financial advice.
    </p>
  </TermsSection>
)

export const TermsContent = () => {
  return (
    <div className="space-y-12">
      <AcceptanceSection />
      <DescriptionSection />
      <IntellectualPropertySection />
      <PrivacySection />
      <TerminationSection />
      <DisclaimersSection />
    </div>
  )
}
